### ISSUE TITLE
Which supy version for citation?

### ISSUE THREAD

**Issue by feigenwinter** [UMEP-dev/SUEWS#246] opened 2024-02-08 10:15 UTC
Hi all,
we had two master thesis started in JAN 2023 that used the supy version 2022.9.22 which was the standard version installed by "pip install supy" at this time. Later we recognized that this version was declared as "yanked" and the current stable version is 2022.4.7. (But the thesis were finished at this time). 
When changing from 2022.9.22 to 2022.4.7 we had to change input parameters to receive similar (but not exactly the same) results as with 2022.9.22. This refers mainly to the input parameter df_state_init.g6 (the soil moisture deficit function) when using df_state_init.gsmodel = 4. (changing from 0.36 (Havu et al., 2022) to 0.05 or so...) This affects QE and FcPhoto.

In #241 sun05 wrote: "However, it is noted a relatively old supy is being used - please do the following:
    update to a recent dev version: pip install supy==2023.7.3.dev0"
Since citing a "yanked" version in a publication is not appropriate, I wonder if citing a "dev"-version is really better?
All this said, we wonder if it's really worth to install and work with a "dev" version, if we can not use the same input parameter values?

**Comment by sunt05** [comment] 2024-02-10 23:32
Hi @feigenwinter, apologies for the inconvenience caused by these changes. We had to yank `v2022.9.22` due to an error in calculating the frontal area index, which becomes significant when tree coverage is large.

Since the formal release of `2022.4.7`, we've been working on numerous under-the-hood improvements and experimental features that are yet to be finalised; hence, please stick with `2022.4.7` for stability.

**Comment by sunt05** [comment] 2024-06-08 21:56
Hopefully, my answer above addresses this issue, so I'll close it for now. Otherwise, feel free to re-open and provide more details to help resolve it.

**Closed by sunt05** 2024-06-08 21:56 UTC
